<a href="https://colab.research.google.com/github/Antony-gitau/probabilistic_AI_playgraound/blob/main/TensorAPI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

directly creating tensor from data

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
x_data


tensor([[1, 2],
        [3, 4]])

In [4]:
import numpy as np
np_arry = np.array(data)
np_arry

array([[1, 2],
       [3, 4]])

from a numpy array

In [6]:
x_np = torch.from_numpy(np_arry)
x_np

tensor([[1, 2],
        [3, 4]])

In [7]:
x_np.device

device(type='cpu')

In [8]:
if torch.cuda.is_available():
  x_np = x_np.to("cuda")

In [9]:
x_np.device

device(type='cpu')

Tensor multiplication


In [10]:
y1 = x_np @ x_np.T
y1

tensor([[ 5, 11],
        [11, 25]])

In [11]:
x_np

tensor([[1, 2],
        [3, 4]])

In [12]:
x_np.T

tensor([[1, 3],
        [2, 4]])

In [13]:
y2 = x_np.matmul(x_np.T)
y2

tensor([[ 5, 11],
        [11, 25]])

In [14]:
z1 = x_np * x_np
z1

tensor([[ 1,  4],
        [ 9, 16]])